# Generated by Django 2.1.8 on 2020-02-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='填写人姓名')),
                ('company', models.CharField(max_length=100, verbose_name='公司名称')),
                ('position', models.CharField(max_length=50, verbose_name='填写人职位')),
                ('contact', models.CharField(max_length=20, verbose_name='联系电话')),
                ('address', models.CharField(max_length=200, verbose_name='公司地址')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='总费用')),
                ('consultation', models.ManyToManyField(blank=True, null=True, to='production.Consultation', verbose_name='咨询产品')),
                ('design', models.ManyToManyField(blank=True, null=True, to='production.Design', verbose_name='设计产品')),
                ('implement', models.ManyToManyField(blank=True, null=True, to='production.Implementation', verbose_name='落地产品')),
                ('marketing', models.ManyToManyField(blank=True, null=True, to='production.Marketing', verbose_name='营销产品')),
            ],
            options={
                'verbose_name': '客户选择表',
                'verbose_name_plural': '客户选择表',
            },
        ),
    ]
