# Generated by Django 2.1.8 on 2020-02-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
        migrations.AddField(
            model_name='question',
            name='status_choice',
            field=models.BooleanField(choices=[(1, '单选'), (0, '多选')], default=0, help_text='默认多选，没啥事不要选择单选', verbose_name='类型（多选或单选）'),
        ),
        migrations.AddField(
            model_name='question',
            name='status_source',
            field=models.BooleanField(choices=[(1, '预设答案'), (2, '客户自定义答案')], default=1, help_text='默认预设，一道题中需要客户全部自定义回答时请选择【客户自定义答案】，选择客户自定义答案时，下方答案不要设置', verbose_name='是否预设答案'),
        ),
    ]
