# Generated by Django 2.1.8 on 2020-02-14 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20200214_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='display_set',
            field=models.BooleanField(choices=[(1, '显示'), (2, '隐藏')], default=1, help_text='默认显示，设置隐藏时客户将看不到这道题', verbose_name='显示设置'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='an_for_question', to='survey.Question', verbose_name='所属问题'),
        ),
    ]
