# Generated by Django 2.1.8 on 2020-02-14 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20200214_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status_extra',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=0, help_text='默认否，设置为是时，题目会生成一个【其他】的自定义选项', verbose_name='是否设置额外回答'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='an_for_question', to='survey.Question', verbose_name='所属问题'),
        ),
        migrations.AlterField(
            model_name='question',
            name='display_set',
            field=models.BooleanField(choices=[(1, '显示'), (0, '隐藏')], default=1, help_text='默认显示，设置隐藏时客户将看不到这道题', verbose_name='显示设置'),
        ),
        migrations.AlterField(
            model_name='question',
            name='status_source',
            field=models.BooleanField(choices=[(1, '预设答案'), (0, '客户自定义')], default=1, help_text='默认预设，一道题中需要客户全部自定义回答时请选择【客户自定义答案】，选择客户自定义答案时，下方答案不要设置', verbose_name='预设答案'),
        ),
    ]
