# Generated by Django 2.1.8 on 2020-02-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20200216_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='answers',
        ),
        migrations.AddField(
            model_name='record',
            name='answers',
            field=models.CharField(default=1, max_length=1024, verbose_name='答案'),
            preserve_default=False,
        ),
    ]
