# Generated by Django 2.1.8 on 2020-02-16 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20200216_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='extra_answer',
        ),
        migrations.RemoveField(
            model_name='record',
            name='other_answer',
        ),
    ]
