# Generated by Django 2.1.8 on 2020-02-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20200216_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='answer_extra',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='自定义回答'),
        ),
        migrations.AddField(
            model_name='record',
            name='answer_other',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='其他回答'),
        ),
    ]
