# Generated by Django 2.1.8 on 2020-02-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20200220_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='record',
            new_name='questions',
        ),
        migrations.RemoveField(
            model_name='record',
            name='answers',
        ),
        migrations.AddField(
            model_name='record',
            name='answers_preset',
            field=models.CharField(default=1, help_text='有客户提交，无须填写', max_length=1024, verbose_name='答案'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='answer_extra',
            field=models.CharField(blank=True, help_text='有客户提交，无须填写', max_length=1024, null=True, verbose_name='自定义回答'),
        ),
        migrations.AlterField(
            model_name='record',
            name='answer_other',
            field=models.CharField(blank=True, help_text='有客户提交，无须填写', max_length=1024, null=True, verbose_name='其他回答'),
        ),
    ]
