# Generated by Django 2.1.8 on 2020-02-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20200220_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='answers_preset',
        ),
        migrations.AddField(
            model_name='record',
            name='answers_preset',
            field=models.ManyToManyField(help_text='有客户提交，无须填写', to='survey.Answer', verbose_name='答案'),
        ),
    ]
