# Generated by Django 2.1.8 on 2020-02-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20200220_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='answers',
        ),
        migrations.AddField(
            model_name='record',
            name='answer_extra',
            field=models.CharField(blank=True, help_text='由客户提交，无须填写', max_length=1024, null=True, verbose_name='自定义回答'),
        ),
        migrations.AddField(
            model_name='record',
            name='answer_other',
            field=models.CharField(blank=True, help_text='由客户提交，无须填写', max_length=1024, null=True, verbose_name='其他回答'),
        ),
        migrations.AddField(
            model_name='record',
            name='answer_preset',
            field=models.CharField(default=1, help_text='由客户提交，无须填写', max_length=1024, verbose_name='答案'),
            preserve_default=False,
        ),
    ]
