# Generated by Django 2.1.8 on 2020-02-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_auto_20200225_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='answer_extra',
            field=models.TextField(blank=True, help_text='由客户提交，无须填写', max_length=1024, null=True, verbose_name='自定义回答'),
        ),
        migrations.AlterField(
            model_name='record',
            name='answer_other',
            field=models.TextField(blank=True, help_text='由客户提交，无须填写', max_length=1024, null=True, verbose_name='其他回答'),
        ),
        migrations.AlterField(
            model_name='record',
            name='answer_preset',
            field=models.TextField(help_text='由客户提交，无须填写', max_length=1024, verbose_name='答案'),
        ),
    ]
